export const tokens = {
  colors: {
    surfaceBase: "var(--color-surface-base)",
    surfacePanel: "var(--color-surface-panel)",
    surfaceCard: "var(--color-surface-card)",
    surfaceOverlay: "var(--color-surface-overlay)",
    gradientPanel: "var(--gradient-panel)",
    shadowInsetGlow: "var(--shadow-inset-glow)",
    bgPrimary: "var(--color-bg-primary)",
    bgSecondary: "var(--color-bg-secondary)",
    textPrimary: "var(--color-text-primary)",
    textSecondary: "var(--color-text-secondary)",
    textMuted: "var(--color-text-muted)",
    textInverse: "var(--color-text-inverse)",
    borderPrimary: "var(--color-border-primary)",
    borderSoft: "var(--color-border-soft)",
    accentPrimary: "var(--color-accent-primary)",
    accentSuccess: "var(--color-accent-success)",
    accentError: "var(--color-accent-error)",
    colorPath: "var(--color-path)",
    chartBar: "var(--color-chart-bar)",
    aws: "var(--color-provider-aws)",
    azure: "var(--color-provider-azure)",
    gcp: "var(--color-provider-gcp)",
    oracle: "var(--color-provider-oracle)",
    ibm: "var(--color-provider-ibm)",
  },
} as const;

export type Tokens = typeof tokens;
